"""Initial migration

Revision ID: 8d49420149ff
Revises: 
Create Date: 2024-10-18 10:14:11.129030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d49420149ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('strava_link', sa.String(length=200), nullable=False),
    sa.Column('rank_name', sa.String(length=50), nullable=False),
    sa.Column('rank_emoji', sa.String(length=10), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('coins_everest', sa.Float(), nullable=False),
    sa.Column('coins_pizza', sa.Float(), nullable=False),
    sa.Column('coins_heartbeat', sa.Integer(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('max_elevation', sa.Float(), nullable=True),
    sa.Column('max_elevation_link', sa.String(length=200), nullable=True),
    sa.Column('max_duration', sa.Float(), nullable=True),
    sa.Column('max_duration_link', sa.String(length=200), nullable=True),
    sa.Column('max_distance', sa.Float(), nullable=True),
    sa.Column('max_distance_link', sa.String(length=200), nullable=True),
    sa.Column('fastest_10k', sa.Float(), nullable=True),
    sa.Column('fastest_10k_link', sa.String(length=200), nullable=True),
    sa.Column('fastest_marathon', sa.Float(), nullable=True),
    sa.Column('fastest_marathon_link', sa.String(length=200), nullable=True),
    sa.Column('fastest_half_marathon', sa.Float(), nullable=True),
    sa.Column('fastest_half_marathon_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_link'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('elevation_gain', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('heartbeats', sa.Integer(), nullable=False),
    sa.Column('coins_everest', sa.Float(), nullable=False),
    sa.Column('coins_pizza', sa.Float(), nullable=False),
    sa.Column('coins_heartbeat', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###
